# -*- coding: utf-8 -*-
"""Assignment1_framework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_RdshvTR6GyrGOqgA0SDStJuqm1Spjw5
"""

import os
import json
import time
from typing import Dict, Any, Optional
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ===== constants =====
UCI_URL = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
REQUIRED_COLS = ["sepal_length", "sepal_width",
                 "petal_length", "petal_width", "species"]
NUM_COLS = ["sepal_length", "sepal_width", "petal_length", "petal_width"]

# ===== logging / utils =====


def log(msg: str, initials: str, student_id: str) -> None:
    """Print a timestamped message tagged with student initials and 9-digit ID."""
    print(f"[{time.strftime('%H:%M:%S')}] [{initials}-{student_id}] {msg}")


def ensure_dir(path: str) -> None:
    """Create directory if it does not exist."""
    os.makedirs(path, exist_ok=True)


# ===== data loader (implementations required) =====
class IrisLoaderUCI:
    def __init__(self, url: str = UCI_URL):
        self.url = url
        self.df: Optional[pd.DataFrame] = None

    def load(self) -> pd.DataFrame:
        df = pd.read_csv(self.url, header=None, names=REQUIRED_COLS,
                         skip_blank_lines=True)  # reading from data file
        self.df = df  # setting the data file to self.df object
        return self.df  # returning object

    def check_class_balance(self) -> Dict[str, Any]:
        class_count = self.df["species"].value_counts().sort_index()
        total = len(self.df)
        count = {}
        proportions = {}
        for key, value in class_count.items():
            count[key] = int(value)
            proportions[key] = round((value/total), 6)
        return {"total": total, "counts": count, "proportions": proportions}

    def save_head(self, k: int = 10, out_csv: str = "./outputs/head.csv", seed: int = None) -> None:

        # deterministically shuffle the DataFrame
        shuffled_df = self.df.sample(frac=1, random_state=seed)
        # get the first k row of the shuffled dataframe
        head_df = shuffled_df.head(k)
        # save the first k rows to CSV without index
        head_df.to_csv(out_csv, index=False)
        return  # successfully saved the head of the DataFrame

    def save_class_balance(self, out_json: str = "./outputs/class_balance.json") -> None:
        class_balance = self.check_class_balance()
        with open(out_json, "w") as f:  # open file in write mode
            json.dump(class_balance, f)  # dumping class balance to JSON file


# ===== processor (implementations required) =====
class Processor:
    def __init__(self, df: pd.DataFrame):
        self.df = df.copy()

    def add_numeric_label(self, out_map: str = "./outputs/label_map.json") -> None:

        species = self.df["species"].sort_values(
        ).tolist()  # sort species alphabetically
        # create a dictionary to map species to numeric labels
        label_map = {v: i for i, v in enumerate(sorted(set(species)))}
        # add numeric label column based on the mapping
        self.df["label"] = self.df["species"].map(label_map)
        with open(out_map, "w") as f:  # dump to JSON file
            json.dump(label_map, f)

    def stats(self) -> Dict[str, Any]:
        stats_dict = {}
        for col in NUM_COLS:
            stats_dict[col] = {
                "min": self.df[col].min(),
                "max": self.df[col].max(),
                "mean": self.df[col].mean(),
                "median": self.df[col].median(),
                "std": self.df[col].std()
            }
        return stats_dict

    def train_val_split(self, val_ratio: float = 0.2, seed=0) -> Dict[str, Any]:

        # deterministically shuffle the DataFrame
        shuffled_df = self.df.sample(frac=1, random_state=seed)
        n = len(shuffled_df)  # total number of rows in the shuffled DataFrame
        # number of validation rows, clamped to at least 1
        n_val = max(1, min(round(n * val_ratio), n - 1))
        validation_shuffle = shuffled_df.iloc[:n_val]
        train_shuffle = shuffled_df.iloc[n_val:]
        train_shuffle.to_csv("./outputs/train.csv", index=False)
        validation_shuffle.to_csv("./outputs/val.csv", index=False)

        return {"train_size": len(train_shuffle), "val_size": len(validation_shuffle)}

    def plot_hist(self, col: str = "petal_length", out: str = "./outputs/hist_petal_length.png") -> None:
        # create histogram for the specified column
        plt.hist(self.df[col], bins=20)
        plt.title(f"Histogram of {col}")
        plt.xlabel(col)
        plt.ylabel("Frequency")
        plt.tight_layout()
        plt.savefig(out, dpi=150)
        plt.close()

    def plot_label_bar(self, out: str = "./outputs/label_bar.png") -> None:
        # include NaN if any, sort by class name
        counts = self.df["species"].value_counts(dropna=False).sort_index()
        plt.bar(counts.index.astype(str), counts.values)
        plt.title("Species Counts")
        plt.xlabel("Species")
        plt.ylabel("Count")
        plt.tight_layout()
        plt.savefig(out, dpi=150)
        plt.close()

    def plot_scatter(self, x: str = "petal_length", y: str = "petal_width",
                     color_by: str = "species", out: str = "./outputs/scatter_petal.png") -> None:
        for group_name, group_df in self.df.groupby(color_by, dropna=False):
            plt.scatter(group_df[x], group_df[y], label=str(group_name))
        plt.title(f"Scatter of {x} vs {y} colored by {color_by}")
        plt.xlabel(x)
        plt.ylabel(y)
        plt.legend()
        plt.tight_layout()
        plt.savefig(out, dpi=150)
        plt.close()

    def save_processed(self, out_csv: str = "./outputs/processed.csv") -> None:
        self.df.to_csv(out_csv, index=False)


# ===== main driver (edit initials/ID,seed) =====
def main(initials: str, student_id: str, seed: int = 0, val_ratio: float = 0.2, uci_url: str = UCI_URL):
    # Validate ID format (exactly 9 digits)
    if not (isinstance(student_id, str) and student_id.isdigit() and len(student_id) == 9):
        raise ValueError(
            "student_id must be a string of exactly 9 digits, e.g., '202312345'.")

    ensure_dir("./outputs")  # must be called exactly once
    log(f"Reading UCI CSV: {uci_url}", initials, student_id)

    loader = IrisLoaderUCI(url=uci_url)
    df = loader.load()
    log(f"Loaded shape: {df.shape}", initials, student_id)

    balance = loader.check_class_balance()
    loader.save_class_balance("./outputs/class_balance.json")
    log(f"Class balance saved: counts={balance.get('counts')}, proportions={balance.get('proportions')}",
        initials, student_id)

    loader.save_head(10, "./outputs/head.csv", seed)
    log("Saved head.csv", initials, student_id)

    proc = Processor(df)
    proc.add_numeric_label("./outputs/label_map.json")
    log("Added numeric label & saved label_map.json", initials, student_id)

    split_info = proc.train_val_split(val_ratio=val_ratio, seed=seed)
    log(f"Split: {split_info}", initials, student_id)

    stats = proc.stats()
    with open("./outputs/stats.json", "w") as f:
        json.dump(stats, f, indent=2)
    log("Saved stats.json", initials, student_id)

    proc.plot_hist("petal_length", "./outputs/hist_petal_length.png")
    proc.plot_label_bar("./outputs/label_bar.png")
    proc.plot_scatter("petal_length", "petal_width",
                      out="./outputs/scatter_petal.png")
    log("Saved plots", initials, student_id)

    proc.save_processed("./outputs/processed.csv")
    log("Saved processed.csv", initials, student_id)


if __name__ == "__main__":
    # === TODO: replace with your own initials and 9-digit student ID,seed

    main(initials="MS", student_id="968892796", seed=int("968892796"[-2:]))
